---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r, echo=TRUE}
library(dplyr)
library(ggplot2)
download.file("https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip", destfile= "C:/Users/overb/OneDrive/Bureau/Coursera/Data Science Specialization/Reproducible Research/Week 2/Assignment/db.zip")
unzip("db.zip")
db <- read.csv("activity.csv")
# changing dates to Date format
db$date <- as.Date(db$date)
```

## What is mean total number of steps taken per day?
```{r, echo=TRUE}
sumdb <- db %>%
  group_by(date) %>%
  summarise(sum = sum(steps, na.rm = T))
hist(sumdb$sum, main= "Histogram of total number of steps each day", xlab= "Number of steps")
paste("Mean:", mean(sumdb$sum), "and median:", median(sumdb$sum),"of number of steps each day")
png("Fig1.png")
hist(sumdb$sum, main= "Histogram of total number of steps each day", xlab= "Number of steps")
dev.off()
```
## What is the average daily activity pattern?
```{r, echo=TRUE}
meandb <- db %>%
  group_by(interval) %>%
  summarise(average = mean(steps, na.rm = T))
with(meandb, plot(interval, average, type= "l"))
paste("Interval:",which.max(meandb$average), "with maximum number of steps:", max(meandb$average))
```

## Imputing missing values
```{r, echo=TRUE}
NAs <- db[is.na(db$steps), ]
paste("Number of missing rows:", length(row.names(NAs)))
#Adding average number of steps for each interval and substituting NAs by average
newdb <- db %>%
  group_by(interval) %>%
  mutate(average_steps= mean(steps, na.rm = T)) %>%
  mutate(new_steps= ifelse(is.na(steps), average_steps, steps))
newdb <- newdb[,c(2,3,5)]

#Redo histogram of total number of steps
sumdb <- newdb %>%
  group_by(date) %>%
  summarise(sum = sum(new_steps))
hist(sumdb$sum, main= "Histogram of total number of steps each day", xlab= "Number of steps")
paste("Mean:", mean(sumdb$sum), "and median:", median(sumdb$sum),"of number of steps each day with imputed missing values")
png("Fig2.png")
hist(sumdb$sum, main= "Histogram of total number of steps each day", xlab= "Number of steps")
dev.off()

```

## Are there differences in activity patterns between weekdays and weekends?
```{r, echo=TRUE}
weekdb <- newdb %>%
  mutate(wkd = ifelse(weekdays(date)== "Saturday"| weekdays(date)=="Sunday", "weekend", "weekday")) %>%
  group_by(interval, wkd) %>%
  summarise(average = mean(new_steps))
weekdb$wkd <- factor(weekdb$wkd)
ggplot(weekdb, aes(x= interval, y= average)) + geom_line() + facet_grid(weekdb$wkd~.)+
  theme_bw()
ggsave("Fig3.png")
```
